# Generated by Django 2.2.4 on 2019-08-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0002_auto_20190819_1523")]

    operations = [
        migrations.AlterField(
            model_name="customtext",
            name="title",
            field=models.CharField(blank=None, max_length=150),
        )
    ]
